apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:DRcDEqhlWfynvMABHjiY,iv:oP8YkRHoPVi28w4x+oihELhrMdCSMeAhaTGnKRfQQkU=,tag:sTe+hMDfbLLV+oqqND98QQ==,type:str]
sops:
  age:
    - recipient: age19hcs9e2avq2s69jlcmltpnz3pvmsp7deuchgfxphtqgzq5eq6plqu7tw2n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTlEwVzlSNDFINXNDV1hG
        cU9MNzR0QklwdzZJWnVJTmJBTndsRC9oMDJzClFrM0h6VnI5WTNSVUVUTW5PdjIw
        ejNTRGhHWVYrTkZhTzh1ekJQcnliWk0KLS0tIEtpSXYwenplL2JKUXQrTjBBMjM2
        enQ5d2UrWENsZFFWb0Q2VHJYU3NZQnMK5rATihTpCTzM6vaJEd6JEaOws5XdO7KO
        ssiRFUz1ZTSJ+4gLyF+fhDqndx0FeZK+EVXg0zY0gmwuzucAbukP7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-13T10:32:42Z"
  mac: ENC[AES256_GCM,data:N8b+C7dpFdm6/HW0/bfnpQRqKrii75ECMFsvyNVRF7Y0OOBTOWZrkwzzO/iT+WcOa3ls7REbjBBmVdcap3SabqA084kGs4+hStrEUw2+WTcYQvqO7VagJgewhVDPBfzaI+rgFutOhQU2DErDsC9i+kwW08YSjlanvGJ/kMz+Mdc=,iv:hIvJ4Qd9yuayI52qypDco6SWviLNnF2ma8oLU5BLn4s=,tag:Vb9I/T9NOFSMojYwqKsZGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
